services:
  - type: web
    name: namma-veedu
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://namma-veedu.onrender.com
      - key: ST_CLIENT_ID
        sync: false
      - key: ST_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
